@ECHO OFF
TITLE LIMPEZA DO SISTEMA...
ECHO.
ECHO PARA INICIAR O PROCESSO DE LIMPEZA DESTA ESTACAO...
PAUSE

CLS
TITLE 1/6 - EFETUANDO LIMPEZA DOS TEMPORARIOS...
ECHO.
ECHO 1/6 - EFETUANDO LIMPEZA DOS TEMPORARIOS...
DEL "%TEMP%" /F /S /Q
CLS
ECHO.
TITLE 1/6 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 1/6 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO.

TITLE 2/6 - EFETUANDO LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER...
ECHO.
ECHO 2/6 - EFETUANDO LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER...
DEL "%USERPROFILE%\LOCALS~1\Temporary Internet Files\Content.IE5" /F /S /Q
CLS
ECHO.
ECHO 1/6 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/6 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO.
TITLE 2/6 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.

TITLE 3/6 - EFETUANDO LIMPEZA DOS TEMPORARIOS DO WINDOWS...
ECHO.
ECHO 3/6 - EFETUANDO LIMPEZA DOS TEMPORARIOS DO WINDOWS...
DEL "%SystemRoot%\Temp" /F /S /Q
CLS
ECHO.
ECHO 1/6 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/6 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO 3/6 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.
ECHO.
TITLE 3/6 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.

TITLE 4/6 - EFETUANDO LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS...
ECHO.
ECHO 4/6 - EFETUANDO LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS...
DEL "%SYSTEMDRIVE%\*.TMP" /F /S /Q
DEL "%SYSTEMDRIVE%\~*.*" /F /S /Q
CLS
ECHO.
ECHO 1/6 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/6 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO 3/6 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.
ECHO 4/6 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.
ECHO.
TITLE 4/6 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.

TITLE 5/6 - EFETUANDO LIMPEZA DOS LOGS...
ECHO.
ECHO 5/6 - EFETUANDO LIMPEZA DOS LOGS...
DEL "%SYSTEMDRIVE%\*.LOG" /F /S /Q
CLS
ECHO.
ECHO 1/7 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/7 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO 3/7 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.
ECHO 4/7 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.
ECHO 5/7 - LIMPEZA DOS LOGS CONCLUIDA.
ECHO.
TITLE 5/7 - LIMPEZA DOS LOGS CONCLUIDA.

TITLE 6/7 - EFETUANDO LIMPEZA DA LIXEIRA...
ECHO.
ECHO 6/7 - EFETUANDO LIMPEZA DA LIXEIRA...
DEL "%SYSTEMDRIVE%\RECYCLER" /F /S /Q
CLS

ECHO 7/7 - EFETUANDO LIMPEZA DA PASTA PREFETCH
DEL C:\WINDOWS\Prefetch\*.* /F /S /Q
CLS

cd "C:\ProgramData\Package Cache"
DEL /F /S *.msiDelete /F /S *.cab

ECHO.
TITLE LIMPEZA CONCLUIDA. 
ECHO 1/7 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/7 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO 3/7 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.
ECHO 4/7 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.
ECHO 5/7 - LIMPEZA DOS LOGS CONCLUIDA.
ECHO 6/7 - LIMPEZA DA LIXEIRA CONCLUIDA.
ECHO 7/7 - LIMPEZA DA PASTA PREFETCH
ECHO.
ECHO.

PAUSE
