
TITLE 4/6 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.

TITLE 5/6 - EFETUANDO LIMPEZA DOS LOGS...
ECHO.
ECHO 5/6 - EFETUANDO LIMPEZA DOS LOGS...
DEL "%SYSTEMDRIVE%\*.LOG" /F /S /Q
CLS
ECHO.
ECHO 1/7 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/7 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO 3/7 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.
ECHO 4/7 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.
ECHO 5/7 - LIMPEZA DOS LOGS CONCLUIDA.
ECHO.
TITLE 5/7 - LIMPEZA DOS LOGS CONCLUIDA.

TITLE 6/7 - EFETUANDO LIMPEZA DA LIXEIRA...
ECHO.
ECHO 6/7 - EFETUANDO LIMPEZA DA LIXEIRA...
DEL "%SYSTEMDRIVE%\RECYCLER" /F /S /Q
CLS

ECHO 7/7 - EFETUANDO LIMPEZA DA PASTA PREFETCH
DEL C:\WINDOWS\Prefetch\*.* /F /S /Q
CLS

cd "C:\ProgramData\Package Cache"
DEL /F /S *.msiDelete /F /S *.cab

ECHO.
TITLE LIMPEZA CONCLUIDA. 
ECHO 1/7 - LIMPEZA DOS TEMPORARIOS CONCLUIDA.
ECHO 2/7 - LIMPEZA DOS TEMPORARIOS DO INTERNET EXPLORER CONCLUIDA.
ECHO 3/7 - LIMPEZA DOS TEMPORARIOS DO WINDOWS CONCLUIDA.
ECHO 4/7 - LIMPEZA DE OUTROS ARQUIVOS TEMPORARIOS CONCLUIDA.
ECHO 5/7 - LIMPEZA DOS LOGS CONCLUIDA.
ECHO 6/7 - LIMPEZA DA LIXEIRA CONCLUIDA.
ECHO 7/7 - LIMPEZA DA PASTA PREFETCH
ECHO.
ECHO.

PAUSE
